bin/index.js
commands/deploy.js
commands/scope.js
index.js
lib/file-list.js
lib/help.js
lib/s3-bucket-factory.js
lib/s3-bucket-params.js
lib/s3-uploader.js
lib/scope.js
package.json
test/file-list.js
test/s3-bucket-factory.js
test/s3-bucket-params.js
test/s3-uploader.js
test/scope.js

- Added s3 region to scope command
- Added basic s3 upload capabilities
- Added tests

CC-4 # Implement deploy

---

README.md
commands/scope.js
docs/usage.md
lib/help.js

- updated usage.md, readme.md and the cli help files

CC-9 # Add usage documentation

---

lib/help.js
package.json

- also add npm public setting to package.json

CC-10 # Update inbuilt cli help

---

commands/deploy.js
package.json

- null is no longer passed as cwd
- bumped version number

CC-14 # Gracefully handle null path parameter

---

.editorconfig
.eslintrc.json
.gitignore
.travis.yml
README.md
appveyor.yml
jsconfig.json
package.json

- ran [@jokeyrhyme/node-init](https://github.com/jokeyrhyme/node-init) for consistency / CI

run @jokeyrhyme/node-init for consistency / CI

---

CHANGELOG.md
README.md
commands/deploy.js
docs/usage.md
lib/help.js
package.json
test/file-read-perf.js
test/s3-bucket-factory.js
test/s3-bucket-params.js
test/scope.js

- Added `--prune` option
- Updated @blinkmobile/aws-s3 to 2.0.0
- Updated tests for new ava api

CC-16 # --prune flag to remove items from remote that are missing locally

---

package.json

fix(package): update aws-sdk to version 2.89.0

---

package.json

fix(package): update aws-sdk to version 2.97.0

---

package.json

fix(package): update aws-sdk to version 2.100.0

---

package.json

fix(package): update aws-sdk to version 2.111.0

---

package.json

fix(package): update aws-sdk to version 2.117.0

---

package.json

fix(package): update aws-sdk to version 2.124.0

---

package.json

fix(package): update aws-sdk to version 2.130.0

---

package.json

fix(package): update aws-sdk to version 2.135.0

---

package.json

fix(package): update aws-sdk to version 2.139.0

---

package.json

fix(package): update aws-sdk to version 2.145.0

---

package.json

fix(package): update aws-sdk to version 2.162.0

---

package.json

fix(package): update aws-sdk to version 2.171.0

---

package.json

fix(package): update aws-sdk to version 2.177.0

---

package.json

fix(package): update aws-sdk to version 2.181.0

---

package.json

fix(package): update aws-sdk to version 2.185.0
